import { Inter } from "next/font/google";

import "./globals.css";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-900`}>
        <Navbar />
        <main className="max-w-2xl min-h-screen container mx-auto flex items-center justify-center pb-5 px-3 pt-20">
          {children}
        </main>
      </body>
    </html>
  );
}
